apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iperf-test

resources:
  - namespace.yaml
  - iperf3-server-deployment.yaml
  - iperf3-server-service.yaml
  - iperf3-client-deployment.yaml
